####### Documentation Folder ########

## Recursively delete documentation directory
if (Test-Path "scenarios") {Remove-Item -Recurse -Force documentation\*.*}

## Check to see if master.json exists
$filename = "scenarios.json"
if (Test-Path $filename) {
    $scenarios = Get-Content $filename | ConvertFrom-Json
} else {
    $scenarios = @('Syslog','Vendors','Azure')
}

Get-Content -Path ".github/templates/readme.md" | Out-File -FilePath ("README.md")

ForEach ($scenario in $scenarios) {

    ## If parent tab does not exist, create it
    If(!(test-path "scenarios\$($scenario)"))
    {
            New-Item -ItemType Directory -Force -Path "scenarios\$($scenario)"
    } else {
        Write-Host "'$($scenario)' folder exists. Skipping scenario folder creation."
    }

    "- [$($scenario)](https://$($env:GITHUB_REPO)/tree/main/documentation/$($scenario))" | Out-file -FilePath ("README.md") -Append
}
