name: Powershell - Create folders

on:
  ['push','workflow_dispatch']

jobs:
  ## Simple Hello World
  Sync_Repo_and_Build:
    name: Sync Repository and build files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github repository
        uses: actions/checkout@v2
      - name: Check to see if documentation.json exists
        shell: pwsh
        run: |
            ####### Documentation Folder ########

            ## Recursively delete documentation directory
            if (Test-Path "scenarios") {Remove-Item -Recurse -Force documentation\*.*}

            ## Check to see if master.json exists
            $filename = "scenarios.json"
            if (Test-Path $filename) {
                $scenarios = Get-Content $filename | ConvertFrom-Json
            } else {
                $scenarios = @('Syslog','Vendors','Azure')
            }

            Get-Content -Path ".github/templates/readme.md" | Out-File -FilePath ("README.md")

            ForEach ($scenario in $scenarios) {

                ## If parent tab does not exist, create it
                If(!(test-path "scenarios\$($scenario)"))
                {
                        New-Item -ItemType Directory -Force -Path "scenarios\$($scenario)"
                } else {
                    Write-Host "'$($scenario)' folder exists. Skipping scenario folder creation."
                }

                ""
                "# $($scenario)" | Out-file -FilePath (Join-Path -Path $scenario -ChildPath "README.md")
                "- [$($scenario)](https://$($env:GITHUB_REPO)/tree/main/documentation/$($scenario))" | Out-file -FilePath ("README.md") -Append
            }
      - name: Configure Github Settings
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: append to file
        run: date >> .github/published.txt
      - name: Check for changes
        run: git status
      - name: Stage changed files
        run: git add .
      - name: Commit changed files
        run: git commit -m "Auto updating published.txt file"
      - name: Push changes
        run: git push