on: [push]

name: AzurePowerShellLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 
      
      - run: |
          Get-AzResource
